# Generated by Django 2.1 on 2019-11-04 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=20)),
                ('good', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
